repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff (lint + autofix)
        entry: ruff check
        language: system
        types: [python]
        stages: [pre-commit]
        args: [--fix]
      - id: ruff-format
        name: ruff-format (black-style formatter)
        entry: ruff format
        language: system
        types: [python]
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: mypy
        name: mypy (type checking)
        entry: mypy
        language: system
        types: [python]
        stages: [pre-commit]
        pass_filenames: false
